name: schedulers
description: Dart library for running asynchronous functions on time. Useful for load balancing, rate limiting, lazy execution.
repository: https://github.com/rtmigo/schedulers

version: 0.3.1

environment:
  sdk: ">=2.18.0 <3.0.0"  # 2.18 needed for test:1.21.6, that is needed to run JS new tests

dependencies:
  meta: ^1.3.0
  collection: ^1.15.0


dev_dependencies:
  test: ^1.21.6
  lints: ^2.0.0
