name: schedulers
description: Dart library for running asynchronous functions on time. Useful for load balancing, rate limiting, lazy execution.
repository: https://github.com/rtmigo/schedulers

version: 0.2.0+0-alpha

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  pedantic: ^1.9.0
  meta: ^1.3.0
  collection: ^1.15.0

dev_dependencies:
  test: ^1.5.1
